version: "3"

networks:
  metao-net:
    driver: bridge
services:

  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - metao-net
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - metao-net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
